### ISSUE TITLE
`sv check` doesn't accept any arguments

### ISSUE THREAD

**Issue by rChaoz** [sveltejs/cli#417]
```shell
$ sv check --tsconfig ./tsconfig.json
> error: too many arguments for 'check'. Expected 0 arguments but got 2.
```

This happens when upgrading from 0.6.11 to 0.6.12. I tried looking at the [changes between these versions](https://github.com/sveltejs/cli/compare/sv%400.6.11...sv%400.6.12) but I can't figure out what's causing it. Looking at the code it seems like this line:

https://github.com/sveltejs/cli/blob/43f73a289b9aa2da685ef15b601ee9f5ffb5b924/packages/cli/commands/check.ts#L13

stopped doing it's job for whatever reason.
